### ISSUE TITLE
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

### ISSUE THREAD

**Issue by welilili** [guapier/zi5book#1]
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

**Comment by guapier** [comment]
@welilili 刚回来上班，我等会抽时间去处理一下。

**Comment by guapier** [comment]
@welilili 是因为你没有科学上网的缘故，我这边可以正常运行。
